// Auto-generated from https://phet.colorado.edu/services/metadata/1.3/simulations
// 119 valid PhET HTML5 simulation IDs (slugs) + their English titles.
// Used by PhETEmbed.tsx for search/autocomplete and URL validation.

export type PhETSim = { id: string; title: string };

export const PHET_SIMS: PhETSim[] = [
  { id: "acid-base-solutions", title: "Acid-Base Solutions" },
  { id: "area-builder", title: "Area Builder" },
  { id: "area-model-algebra", title: "Area Model Algebra" },
  { id: "area-model-decimals", title: "Area Model Decimals" },
  { id: "area-model-introduction", title: "Area Model Introduction" },
  { id: "area-model-multiplication", title: "Area Model Multiplication" },
  { id: "arithmetic", title: "Arithmetic" },
  { id: "atomic-interactions", title: "Atomic Interactions" },
  { id: "balancing-act", title: "Balancing Act" },
  { id: "balancing-chemical-equations", title: "Balancing Chemical Equations" },
  { id: "balloons-and-static-electricity", title: "Balloons and Static Electricity" },
  { id: "beers-law-lab", title: "Beer\'s Law Lab" },
  { id: "bending-light", title: "Bending Light" },
  { id: "blackbody-spectrum", title: "Blackbody Spectrum" },
  { id: "build-a-fraction", title: "Build a Fraction" },
  { id: "build-a-molecule", title: "Build a Molecule" },
  { id: "build-a-nucleus", title: "Build a Nucleus" },
  { id: "build-an-atom", title: "Build an Atom" },
  { id: "buoyancy", title: "Buoyancy" },
  { id: "buoyancy-basics", title: "Buoyancy: Basics" },
  { id: "calculus-grapher", title: "Calculus Grapher" },
  { id: "capacitor-lab-basics", title: "Capacitor Lab: Basics" },
  { id: "center-and-variability", title: "Center and Variability" },
  { id: "charges-and-fields", title: "Charges and Fields" },
  { id: "circuit-construction-kit-ac", title: "Circuit Construction Kit: AC" },
  { id: "circuit-construction-kit-ac-virtual-lab", title: "Circuit Construction Kit: AC - Virtual Lab" },
  { id: "circuit-construction-kit-dc", title: "Circuit Construction Kit: DC" },
  { id: "circuit-construction-kit-dc-virtual-lab", title: "Circuit Construction Kit: DC - Virtual Lab" },
  { id: "collision-lab", title: "Collision Lab" },
  { id: "color-vision", title: "Color Vision" },
  { id: "concentration", title: "Concentration" },
  { id: "coulombs-law", title: "Coulomb\'s Law" },
  { id: "curve-fitting", title: "Curve Fitting" },
  { id: "density", title: "Density" },
  { id: "diffusion", title: "Diffusion" },
  { id: "energy-forms-and-changes", title: "Energy Forms and Changes" },
  { id: "energy-skate-park", title: "Energy Skate Park" },
  { id: "energy-skate-park-basics", title: "Energy Skate Park: Basics" },
  { id: "equality-explorer", title: "Equality Explorer" },
  { id: "equality-explorer-basics", title: "Equality Explorer: Basics" },
  { id: "equality-explorer-two-variables", title: "Equality Explorer: Two Variables" },
  { id: "expression-exchange", title: "Expression Exchange" },
  { id: "faradays-electromagnetic-lab", title: "Faraday\'s Electromagnetic Lab" },
  { id: "faradays-law", title: "Faraday\'s Law" },
  { id: "forces-and-motion-basics", title: "Forces and Motion: Basics" },
  { id: "fourier-making-waves", title: "Fourier: Making Waves" },
  { id: "fraction-matcher", title: "Fraction Matcher" },
  { id: "fractions-equality", title: "Fractions: Equality" },
  { id: "fractions-intro", title: "Fractions: Intro" },
  { id: "fractions-mixed-numbers", title: "Fractions: Mixed Numbers" },
  { id: "friction", title: "Friction" },
  { id: "function-builder", title: "Function Builder" },
  { id: "function-builder-basics", title: "Function Builder: Basics" },
  { id: "gas-properties", title: "Gas Properties" },
  { id: "gases-intro", title: "Gases Intro" },
  { id: "gene-expression-essentials", title: "Gene Expression Essentials" },
  { id: "generator", title: "Generator" },
  { id: "geometric-optics", title: "Geometric Optics" },
  { id: "geometric-optics-basics", title: "Geometric Optics: Basics" },
  { id: "graphing-lines", title: "Graphing Lines" },
  { id: "graphing-quadratics", title: "Graphing Quadratics" },
  { id: "graphing-slope-intercept", title: "Graphing Slope-Intercept" },
  { id: "gravity-and-orbits", title: "Gravity and Orbits" },
  { id: "gravity-force-lab", title: "Gravity Force Lab" },
  { id: "gravity-force-lab-basics", title: "Gravity Force Lab: Basics" },
  { id: "greenhouse-effect", title: "Greenhouse Effect" },
  { id: "hookes-law", title: "Hooke\'s Law" },
  { id: "isotopes-and-atomic-mass", title: "Isotopes and Atomic Mass" },
  { id: "john-travoltage", title: "John Travoltage" },
  { id: "keplers-laws", title: "Kepler\'s Laws" },
  { id: "least-squares-regression", title: "Least-Squares Regression" },
  { id: "magnet-and-compass", title: "Magnet and Compass" },
  { id: "magnets-and-electromagnets", title: "Magnets and Electromagnets" },
  { id: "make-a-ten", title: "Make a Ten" },
  { id: "masses-and-springs", title: "Masses and Springs" },
  { id: "masses-and-springs-basics", title: "Masses and Springs: Basics" },
  { id: "mean-share-and-balance", title: "Mean: Share and Balance" },
  { id: "membrane-transport", title: "Membrane Transport" },
  { id: "models-of-the-hydrogen-atom", title: "Models of the Hydrogen Atom" },
  { id: "molarity", title: "Molarity" },
  { id: "molecule-polarity", title: "Molecule Polarity" },
  { id: "molecule-shapes", title: "Molecule Shapes" },
  { id: "molecule-shapes-basics", title: "Molecule Shapes: Basics" },
  { id: "molecules-and-light", title: "Molecules and Light" },
  { id: "my-solar-system", title: "My Solar System" },
  { id: "natural-selection", title: "Natural Selection" },
  { id: "neuron", title: "Neuron" },
  { id: "number-compare", title: "Number Compare" },
  { id: "number-line-distance", title: "Number Line: Distance" },
  { id: "number-line-integers", title: "Number Line: Integers" },
  { id: "number-line-operations", title: "Number Line: Operations" },
  { id: "number-pairs", title: "Number Pairs" },
  { id: "number-play", title: "Number Play" },
  { id: "ohms-law", title: "Ohm\'s Law" },
  { id: "pendulum-lab", title: "Pendulum Lab" },
  { id: "ph-scale", title: "pH Scale" },
  { id: "ph-scale-basics", title: "pH Scale: Basics" },
  { id: "plinko-probability", title: "Plinko Probability" },
  { id: "projectile-data-lab", title: "Projectile Data Lab" },
  { id: "projectile-motion", title: "Projectile Motion" },
  { id: "projectile-sampling-distributions", title: "Projectile Sampling Distributions" },
  { id: "proportion-playground", title: "Proportion Playground" },
  { id: "quadrilateral", title: "Quadrilateral" },
  { id: "quantum-coin-toss", title: "Quantum Coin Toss" },
  { id: "quantum-measurement", title: "Quantum Measurement" },
  { id: "ratio-and-proportion", title: "Ratio and Proportion" },
  { id: "reactants-products-and-leftovers", title: "Reactants, Products and Leftovers" },
  { id: "resistance-in-a-wire", title: "Resistance in a Wire" },
  { id: "rutherford-scattering", title: "Rutherford Scattering" },
  { id: "states-of-matter", title: "States of Matter" },
  { id: "states-of-matter-basics", title: "States of Matter: Basics" },
  { id: "trig-tour", title: "Trig Tour" },
  { id: "under-pressure", title: "Under Pressure" },
  { id: "unit-rates", title: "Unit Rates" },
  { id: "vector-addition", title: "Vector Addition" },
  { id: "vector-addition-equations", title: "Vector Addition: Equations" },
  { id: "wave-interference", title: "Wave Interference" },
  { id: "wave-on-a-string", title: "Wave on a String" },
  { id: "waves-intro", title: "Waves Intro" },
];

// Quick O(1) lookup: slug → exists
export const PHET_SIM_IDS = new Set(PHET_SIMS.map(s => s.id));
